import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import ReactQueryClientProvider from "@/providers/ReactQueryClientProvider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import { ShoppingCartProvider } from "@/contexts/ShoppingCartContext";
import Navbar from "@/components/Navbar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
        className="overflow-x-hidden"
      >
        <Toaster closeButton />
        <NuqsAdapter>
          <ReactQueryClientProvider>
            {children}
            <ReactQueryDevtools
              initialIsOpen={false}
              buttonPosition="bottom-left"
            />
          </ReactQueryClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  );
}
